### ISSUE TITLE
MusicRandomizer is still in the AIO

### ISSUE THREAD

**Issue by OatmealDome** [MCMiners9/Splat-AIO#30]
#### Describe your issue

MusicRandomizer is *still* included in the AIO despite multiple requests for removal.

#### What version of SplatAIO are you running?

N/A 

#### What operating system are you on?

N/A

#### What steps did you take to replicate this issue?

N/A

#### Is this relating to a specific hack in the AIO?

N/A

**Comment by DeckOfNoobs** [comment]
forgot I still had that in there, lol, will remove when I can

**Comment by DeckOfNoobs** [comment]
forgot I still had that in there, lol, will remove when I can

**Comment by MCMiners9** [comment]
I can't take care of this as 1) I put deck of noobs in charge and 2) I dont have my pc with me

**Comment by MCMiners9** [comment]
@OatmealDome I have removed Sisterhax, Splat-AIO 2, and MusicRandomizer at your request. I'll now close this issue, if you have any other issues please make a new issue by [clicking here](https://github.com/MCMiners9/Splat-AIO/issues/new)
