### ISSUE TITLE
Extra Folder in Resources is Missing

### ISSUE THREAD

**Issue by DeckOfNoobs** [MCMiners9/Splat-AIO#4]
This breaks Sisterhax and credits. FIXING IS TOP PRIORITY

**Comment by MCMiners9** [comment]
I am working on finding out how to restore it, should be fixed by v22 or v23.

**Comment by MCMiners9** [comment]
Which SplatAIO version is this? I just recently released v21 and after publishing it, I read this. You can view the v21 changelog by clicking [here.](https://github.com/MCMiners9/Splat-AIO/releases

**Comment by MCMiners9** [comment]
Could you fix this issue in v22? Thank you. I can't find Sisterhax on the Modding Hub thread, they completely remodeled it.

**Comment by DeckOfNoobs** [comment]
finally fixed

**Comment by MCMiners9** [comment]
Yep
